### ISSUE TITLE
基础组件starter项目模块啥时候开源

### ISSUE THREAD

**Issue by loong024** [shuigedeng/taotao-cloud-project#21]
# 版本信息 （必填）：
当前使用的版本（必填）：3.1.X 或其它
JDK 版本(必填) : JDK 21 一定写明至具体的小版本号
使用的数据库及版本(必填)： PostgreSQL X or MySQL 5.X / 8.X

# 问题描述：

# 报错截图

# 日志信息

# 重现步骤
1. 出错前自己做了哪些操作及具体步骤，包括修改了哪些地方、是否编译代码等
2. 访问了什么接口？
3. 传递什么参数？
4. 后端控制台报了什么错？
5. 前端控制台报了什么错？
6. 原来用的什么版本？现在升级到了什么版本？
7. 启动报错还是运行报错？ 运行报错是调用了那个接口？

**Comment by shuigedeng** [comment]
暂时还没有计划开源 不过在maven center有发布的包
