### ISSUE TITLE
starter项目模块 后续是否开源

### ISSUE THREAD

**Issue by cnrainbing** [shuigedeng/taotao-cloud-project#48]
12.基础组件starter项目模块 (暂未开源)

1. 看你了您的作品写的非常好，代码质量很高、希望作者走开源路线
2. 有没有Demo 样例或者第三方哪个开源项目使用了咱们产品

**Comment by shuigedeng** [comment]
1.暂无计划开源
2.taotao-cloud-ddd 或者项目中microservice中就是demo样例  目前还没有第三方项目使用
